#!/bin/sh

sbt dist:clean
sbt dist

AKKA_HOME="$(cd target/dist; pwd)"
AKKA_CLASSPATH="$AKKA_HOME/config:$AKKA_HOME/lib/*"
JAVA_OPTS="-Xms256M -Xmx1024M -XX:+UseParallelGC"

function clusterNode {
  java $JAVA_OPTS -cp "$AKKA_CLASSPATH" -Dakka.home="$AKKA_HOME" -Dakka.remote.netty.tcp.port=$1 akka.kernel.Main cakesolutions.example.ClusterNodeApplication &
}

# We start 3 JVMs (each JVM will be a cluster node)
clusterNode 6666
clusterNode 7788
clusterNode 9999

sbt console

killall java
